--
-- Koki ASAUMI <roomikiru@gmail.com>
--
SET CHARSET UTF8;
CREATE DATABASE IF NOT EXISTS nago DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;
CREATE USER 'www'@'%' IDENTIFIED BY 'NFc58T&4!EFk1';
GRANT SELECT, INSERT, UPDATE, DELETE ON nago.* to 'www'@'%';
USE nago;
