db:
  provider: "mysql"
  host: "nago-mysql"
  port: 3306
  user: "www"
  password: "NFc58T&4!EFk1"
  dbname: "nago"

redis:
  host: "nago-redis"
  port: 6379

server:
  port: 8081

mail:
  from: "nago-support-dev@gmail.com"
  host: "nago-maildev"
  port: 1025
  insecureSkipVerify: true

url:
  front: "localhost:3001"
  server: "localhost:8081"
