db:
  provider: "mysql"
  host: "nago.ckylqwra3xqd.ap-northeast-1.rds.amazonaws.com"
  port: 3306
  user: "root"
  password: "bongo2204"
  dbname: "nago"

server:
  port: 8081

mail:
  from: "nago-support-dev@gmail.com"
  host: "nago-maildev"
  port: 1025
  insecureSkipVerify: true

domain:
  front: "localhost:3001"
  server: "localhost:8081"

url:
  front: "http://localhost:3001"
  server: "http://localhost:8081"
