db:
  provider: "mysql"
  host: "nago-mysql"
  port: "3306"
  user: "www"
  password: "NFc58T&4!EFk1"
  dbname: "nago"

redis:
  host: "nago-redis"
  port: "6379"
  sessionKey: "nago-session"
  password: "rIguo7jfxkMjA5Il6RyG"

server:
  port: "8081"

mail:
  from: "nago-support-dev@gmail.com"
  host: "nago-maildev"
  port: "1025"
  insecureSkipVerify: true

url:
  main: "localhost:3001"
